### ISSUE TITLE
Possible to update pip in the public.ecr.aws/sam/build-python3.6 build image?

### ISSUE THREAD

**Issue by camlow325** [aws/aws-sam-build-images#11]
The version of pip installed in the `public.ecr.aws/sam/build-python3.6` image currently is `18.1`. As mentioned in this [`psycopg2` project issue](https://github.com/psycopg/psycopg2/issues/1290), older versions of `pip` (which include `18.1`) fail to install the latest `psycopg2` versions (`2.9` or later).

If we upgrade to the latest `pip` version, `21.1.2`, we are able to install the later `psycopg2` versions without issues. Would it be possible to upgrade the default `pip` version in the `public.ecr.aws/sam/build-python3.6` image to the latest version?

**Comment by hoffa** [comment]
You can `pip install --upgrade pip` for your use case, but I'd be somewhat wary of doing that by default for all consumers, as it's essentially upgrading the system `pip` (provided by the `python3-pip` Amazon Linux package) outside the package manager. Also, [Python 3.6 is EOL](https://devguide.python.org/#status-of-python-branches), so it would be beneficial to move a more recent release, which include more recent `pip` releases as well.
