### ISSUE TITLE
docker image does not include libffi.so.6 needed for Python 3.11

### ISSUE THREAD

**Issue by georgetakla** [aws/aws-sam-build-images#117]
### Description:
libffi.so.6 is missing from the python3.11 latest image

using vscode launch config to run sam local invoke create the image and acquires public.ecr.aws/sam/emulation-python3.11. after mounting the image and starting the code, if fails to start the session and the output presents
`Traceback (most recent call last):
  File "/tmp/lambci_debug_files/py_debug_wrapper.py", line 46, in <module>
    runpy.run_module('debugpy', run_name='__main__')
  File "<frozen runpy>", line 229, in run_module
  File "<frozen runpy>", line 88, in _run_code
  File "/var/task/debugpy/__main__.py", line 37, in <module>
    from debugpy.server import cli
  File "/var/task/debugpy/server/__init__.py", line 7, in <module>
    import debugpy._vendored.force_pydevd  # noqa
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/task/debugpy/_vendored/force_pydevd.py", line 44, in <module>
    preimport('pydevd', [
  File "/var/task/debugpy/_vendored/__init__.py", line 126, in preimport
    import_module(name)
  File "/var/lang/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/task/debugpy/_vendored/pydevd/pydevd.py", line 45, in <module>
    from _pydevd_bundle import pydevd_utils
  File "/var/task/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_utils.py", line 9, in <module>
    import ctypes
  File "/var/lang/lib/python3.11/ctypes/__init__.py", line 8, in <module>
    from _ctypes import Union, Structure, Array
ImportError: libffi.so.6: cannot open shared object file: No such file or directory
05 Dec 2023 21:07:19,654 [ERROR] (rapid) Init failed error=Runtime exited with error: exit status 1 InvokeID=`

### Steps to reproduce:
attached is a zip file of the sample lambda created with sam init  (Note: I included 3.11, and 3.9 venv for reference)
[lambda-test.zip](https://github.com/aws/aws-sam-build-images/files/13574244/lambda-test.zip)
actions to produce the error
1- in the template .yaml; change the  function Runtime: from  python3.9 to python3.11 
2- from vscode debug, launch lambda-test:HelloWorldFunction (python3.11)
Note: the error disappears when launch vscode after changing the Runtime to  python3.9 in template.yaml

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: MacOS
2. If using SAM CLI, `sam --version`: 1.99.0
3. AWS region: us-east-1

**Comment by jysheng123** [comment]
Hi, thanks for bringing up the issue. It seems that https://gallery.ecr.aws/lambda/python made a release that has issues and should be fixed next release. Until then we have a mitigation. As you can see in the documentation (https://docs.aws.amazon.com/toolkit-for-vscode/latest/userguide/serverless-apps-run-debug-config-ref.html), there is a field is launch.json sam properties called skipNewImageCheck. Add this to your launch.json and set it to be true. Then you have to manually delete the images on your docker locally, both [public.ecr.aws/lambda/python:3.11-rapid-x86_64](http://public.ecr.aws/lambda/python:3.11-rapid-x86_64) and [public.ecr.aws/lambda/python:3.11-x86_64](http://public.ecr.aws/lambda/python:3.11-x86_64). After deleting it, you can then pull an older version of the image on their website, for my example I used [public.ecr.aws/lambda/python:3.11.2023.11.18.02-x86_64](http://public.ecr.aws/lambda/python:3.11.2023.11.18.02-x86_64) (change architecture to match yours). After that you have to retag the image to the x86-64 tag itself. Therefore the command should be `docker tag <YOUR IMAGE ID> public.ecr.aws/lambda/python:3.11-x86_64`. After that, running the debugger should work properly.

After running the steps this is what a sample launch.json and `docker images` command should output:
`{
    "configurations": [
        {
            "type": "aws-sam",
            "request": "direct-invoke",
            "name": "test",
            "invokeTarget": {
                "target": "code",
                "projectRoot": "hello_world",
                "lambdaHandler": "app.lambda_handler"
            },
            "lambda": {
                "runtime": "python3.11",
                "payload": {},
                "environmentVariables": {}
            },
            "sam": {
                "skipNewImageCheck": true
            }
        }
    ]
}`
`docker images` command ouput:
`public.ecr.aws/lambda/python   3.11-x86_64                 3e02a31fb67a   2 weeks ago     752MB
public.ecr.aws/lambda/python   3.11.2023.11.18.02-x86_64   3e02a31fb67a   2 weeks ago     752MB`

Please let me know if you have any questions or any issues still. Thanks

**Comment by georgetakla** [comment]
Thank you jysheng123!
I followed the steps and provided the action log for reference
[docker_images_updates.txt](https://github.com/aws/aws-sam-build-images/files/13588258/docker_images_updates.txt)

I noticed in the (https://docs.aws.amazon.com/toolkit-for-vscode/latest/userguide/serverless-apps-run-debug-config-ref.html), that we can define for sam the build-image. I have not tested this approach yet and I wonder if you recommend it for specific cases

config will be like 
`{ "configurations": [ { "type": "aws-sam", "request": "direct-invoke", "name": "test", "invokeTarget": { "target": "code", "projectRoot": "hello_world", "lambdaHandler": "app.lambda_handler" }, "lambda": { "runtime": "python3.11", "payload": {}, "environmentVariables": {} }, "sam": { "skipNewImageCheck": true, "build-image": "http://public.ecr.aws/lambda/python:3.11-x86_64" } } ] } `

**Comment by jysheng123** [comment]
Hi, well turns out the mitigation will not be needed as the lambda aws team has fixed the issue on their side so your original debugger should be working just fine now, I tested it on mine and it works properly. Let me know if your issue is fixed and in regards to your approach, I don't believe there is a [build option ](https://docs.aws.amazon.com/toolkit-for-vscode/latest/userguide/serverless-apps-run-debug-config-ref.html) in sam for `build-image`. If you want to be able to pass in your custom image, I suggest you do something similar to the mitigation I was talking about, as in tag your custom image as the image that it is looking for (in this case public.ecr.aws/lambda/python:3.11-x86_64) then pass in the skipNewImageCheck as True then it should be using that image. Let me know if your debugger is working properly now.

**Comment by georgetakla** [comment]
Hi,  
1- the mitigation is working for me, thank you!. I did not test the updated image yet
2- in the buildArguments of [build option ](https://docs.aws.amazon.com/toolkit-for-vscode/latest/userguide/serverless-apps-run-debug-config-ref.html), it points to [sam build](https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-cli-command-reference-sam-build.html) that has build-image
