### ISSUE TITLE
Yarn

### ISSUE THREAD

**Issue by stephenbawks** [aws/aws-sam-build-images#12]
Any chance we cannot get yarn added into these containers as well?

**Comment by hoffa** [comment]
The [Lambda Builders library](https://github.com/aws/aws-lambda-builders) used by `sam build` to create Lambda deployment artifacts is designed to work with npm, so unless SAM supports Yarn natively, I'd be wary of introducing it by default. As alternative you can of course `npm install -g yarn`.
