### ISSUE TITLE
Add .NET runtimes

### ISSUE THREAD

**Issue by 1davidmichael** [aws/aws-sam-build-images#13]
### Description
Currently there are not provided docker images for the .NET runtime, and the [sam build command does not support the `--use-container` flag](https://github.com/aws/aws-sam-cli/pull/1096). This makes typical build and deploy workflows with SAM not working consistently for .NET projects. It would be great if a Docker image could be provided and the [sam cli](https://github.com/aws/aws-sam-cli) updated to work with the container.

### Benefits
Ensures consistent behavior for all [AWS Lambda supported runtimes](https://docs.aws.amazon.com/lambda/latest/dg/lambda-runtimes.html) by the AWS SAM cli and build/deploy workflow.

### Request

Add .NET Dockerfiles supporting AWS runtimes

- Dockerfile-dotnetcore31
- Dockerfile-dotnetcore21

**Comment by chrisoverzero** [comment]
It's especially confusing that [such a container][dotnet] is listed on the ECR Public Gallery, but has no data/tags associated with it.

[dotnet]:https://gallery.ecr.aws/sam/build-dotnetcore3.1

> This makes typical build and deploy workflows with SAM not working consistently for .NET projects.

Even more than consistency, this lack prevents certain optimizations for .NET Lambda Functions. Deploying an application as `ReadyToRun` helps startup times significantly. To do it, the application has to be built on the deployment target (barring some limited cross-compilation). This is much easier with an official SAM build image.

**Comment by mr-davidc** [comment]
Will this issue also cover introducing an AWS SAM build image for `net5.0` ?

**Comment by chrisoverzero** [comment]
I do not intend to, at least. `net5.0` is not a supported [Lambda runtime](https://docs.aws.amazon.com/lambda/latest/dg/lambda-runtimes.html).

**Comment by mr-davidc** [comment]
Yea of course @chrisoverzero.

I was thinking perhaps an AW SAM build image for `net5.0` would **only** be for building Lambdas targeting `net5.0` with `PackageType: Image`. Kind of like you can do using the AWS SAM CLI on your local machine.

**Comment by ssenchenko** [comment]
Image for .NET Core 3.1 merged. Closing this issue. 
There are no plans to add  .NET Core 2.1 or .NET 5
