### ISSUE TITLE
Emulation images

### ISSUE THREAD

**Issue by sahidvelji** [aws/aws-sam-build-images#147]
How can I contact the team responsible for maintaining and publishing the emulation images?

It looks like the team has not published a `sam/emulation-provided.al2023` image like they did for `provided.al2`.
I do see these:
`sam/emulation-provided.al2`
`sam/build-provided.al2`
`sam/build-provided.al2023`
But I can’t seem to find any information as to why there is no `emulation-provided.al2023` image.
https://gallery.ecr.aws/sam?page=1

**Comment by mndeveci** [comment]
Hi @sahidvelji Lambda team was responsible to publish those images. But for the past year or so, we are using the Lambda Base images directly, which is maintained in this repository https://github.com/aws/aws-lambda-base-images

May I ask why you need the emulation images? Lambda Base images should be sufficient to run lambda functions locally.

**Comment by sahidvelji** [comment]
Thanks @mndeveci I don't necessarily need the emulation images. I was more just curious about the reason.

**Comment by mndeveci** [comment]
Got it, as I mentioned above, the Lambda Base Images should be sufficient enough for local emulation. I am going to resolve this issue now but please let us know if you have other questions.
