### ISSUE TITLE
Missing Yum on Node Build Images

### ISSUE THREAD

**Issue by metaskills** [aws/aws-sam-build-images#16]
I have noticed that both of these images are missing `yum` where all the other SAM build images have it.

* amazon/aws-sam-cli-build-image-nodejs12.x
* amazon/aws-sam-cli-build-image-nodejs14.x

Yum is also installed on each Lambda runtime `public.ecr.aws/lambda/...` (including the node versions above) images and our tooling requires that they also be on the build image. Thinking it is a big oversight that somehow these are missing?

**Comment by hoffa** [comment]
Thanks for reporting this! The ECR images now include `yum`.

**Comment by metaskills** [comment]
Thanks! I can confirm they are now in these images:

* public.ecr.aws/sam/build-nodejs12.x
* public.ecr.aws/sam/build-nodejs14.x

Not seeing them in the older versions in the desc above but that is fine, I think we should be moving to these newer ones anyway. Cheers!

**Comment by hoffa** [comment]
Thanks! The DockerHub images have also been updated.
