### ISSUE TITLE
Please add rsync to images

### ISSUE THREAD

**Issue by shellscape** [aws/aws-sam-build-images#3]
Hey folks, hoping someone can step in and add rsync to the list of packages that `yum` installs. Tried to get around this using `yum` in the commands I'm passing to the container, but there's some funkiness going on there and bash can't find it.

**Comment by shellscape** [comment]
It's worth noting that even the CDK team has had to work around a lack of this being installed https://github.com/aws/aws-cdk/pull/9763, which seems a bit bananas to me.

**Comment by hoffa** [comment]
Hey! This is certainly something we could consider. To understand better, would you mind sharing your use case for using `rsync`?

**Comment by shellscape** [comment]
@hoffa not sure you saw my last comment.

the use case is preventing your own compadres from having to use inferior file manipulation tools because `rsync` isn't included in the SAM images. The SAM images are being used here https://github.com/aws/aws-cdk/blob/e2e008bd19c3ff1b08ccb093dba576551ec73240/packages/%40aws-cdk/aws-lambda/lib/runtime.ts#L227 and `cp` is twice as slow as `rsync` for large projects. Anyone wishing to roll their own bundling logic is forced to either 1. use an out-of-band custom docker image (which we've opted for in the meantime, and is a hassle) or 2. use a slower method.

`rsync` isn't going to add any significant dependencies or bloat, so I'm a bit curious why there's a need for a sell on use case. See: https://github.com/aws/aws-codebuild-docker-images/blob/master/al2/x86_64/standard/1.0/Dockerfile#L39

**Comment by hoffa** [comment]
Thanks for the details. I'm trying to understand how you're using the build image, as typically they're used by SAM CLI when building apps with `sam build --use-container`.

**Comment by shellscape** [comment]
You need but follow the links to the CDK project I've provided to understand how they're being used. I linked directly to the source - they're using the same images to bundle lambdas. I'm admittedly a bit frustrated that you're missing the connection there. Is there another maintainer you can bring in to bridge the gap here, or perhaps reach out to the AWS CDK team members that were stymied by the lack of rsync in the image?

**Comment by hoffa** [comment]
Gotcha, was curious whether there were any custom use cases as the build images are sometimes used in interesting ways. I'll check with the team, but this seems reasonable to me and the footprint is small.

**Comment by hoffa** [comment]
We've released new build images that include `rsync`. Thanks for raising this!

**Comment by shellscape** [comment]
Much appreciated
