### ISSUE TITLE
Update Go?

### ISSUE THREAD

**Issue by nevins-b** [aws/aws-sam-build-images#43]
Golang's current stable version is [1.17.5](https://go.dev/dl/), the current image is still on 1.16.5. Can we get this version updated?

**Comment by hoffa** [comment]
Thanks for the heads-up! Published a PR.

**Comment by hoffa** [comment]
Released:

```bash
% docker run --rm public.ecr.aws/sam/build-go1.x go version
go version go1.17.5 linux/amd64
```
