### ISSUE TITLE
Make emulation base images available

### ISSUE THREAD

**Issue by corymhall** [aws/aws-sam-build-images#47]
CDK users have reported [an issue](https://github.com/aws/aws-cdk/issues/12610#issuecomment-934694469) with the sam build images that causes building to fail if they are using `btrfs` or `zfs` storage drivers. The suggested resolution is to update the root mode which can only be done in the base image. 

Are those base image Dockerfiles (i.e. `public.ecr.aws/sam/emulation-python3.9`) available anywhere?

**Comment by moelasmar** [comment]
Thanks @corymhall for raising this issue. The emulation images are managed by a different team. I will share this issue with them.

**Comment by jfuss** [comment]
`public.ecr.aws/sam/emulation-python3.9` are not managed within this repo but by the Lambda team. I will reach out internally.

Closing as this issues is not related to the build images.
