### ISSUE TITLE
What happened with aws-sam-cli-build-image-nodejs16.x

### ISSUE THREAD

**Issue by marcelloceschia** [aws/aws-sam-build-images#58]
### Description:

Some month ago we was deploying our function using nodejs16 image version. Now it's not available anymore. The repository still contains the Dockerfile for building this image, but it looks like it's excluded to be pushed.

**Comment by hoffa** [comment]
You should use the [`build-nodejs16.x` image in ECR Public Gallery](https://gallery.ecr.aws/sam/build-nodejs16.x) (`public.ecr.aws/sam/build-nodejs16.x`) instead. See [here](https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-image-repositories.html) for the list of images; newest images are all in the ECR repositories.
