### ISSUE TITLE
Feature request: Add docker to images

### ISSUE THREAD

**Issue by Bradger77** [aws/aws-sam-build-images#59]
### Describe your idea/feature/enhancement

I wish AWS SAM build images would have Docker installed on them.

For Lambdas that are run with a container (i.e. `PackageType`=`Image`), AWS SAM can build and push images to ECR (or other image repos). But you can only do this if docker is installed, and if you are logged in with docker. In order for the AWS SAM build images to support container-lambdas being built and pushed with AWS SAM, it would be great to have docker installed on them.

I am trying to `sam package` an image to ECR from a CI/CD CodePipeline, similar to the process described
[here](https://aws.amazon.com/blogs/compute/using-container-image-support-for-aws-lambda-with-aws-sam/).

I'm using sam/build-python3.9, where docker is not installed.

Obvious workarounds are either to create your own image off these, or to install and start docker when running the image. But given that pushing images is an AWS SAM feature, it would be great for these images to support that feature out of the box.

**Comment by lucashuy** [comment]
Hi, thanks for raising this issue! Is it possible to mount the Docker socket from the host machine to the Docker container instead of trying to install and use Docker inside of Docker?

This can be done by appending `-v /var/run/docker.sock:/var/run/docker.sock` to your docker command, or with
```
volumes:
  - /var/run/docker.sock:/var/run/docker.sock  
```
if you are using docker-compose.

**Comment by lucashuy** [comment]
Closing this issue, please re-open or create a new issue if you have any other concerns or feedback for the team!
