### ISSUE TITLE
[Question] enable unit test on Bitbucket Pipelines and using npm/npx

### ISSUE THREAD

**Issue by danhnguyeen** [aws/aws-sam-build-images#83]
Hi there!

I'm using `sam pipeline init --bootstrap` and have two bellow concerns, could you please help me to clarify:
**1, How to run `npm` in pipeline?** 
I need to implement `migrate database` step on **Bitbucket Pipelines**. I'm using `sequelize-cli` so I need to run a command something like `npx sequelize-cli db:migrate`
But it seems `node` is not existing in this image. So I tried to install `node 18` by myself but it throws this error `GLIBC_2.28' not found`. 
I downgrade to `node 16` and it is ok now. But this is not what I expected. 
So could you please tell me what is the best way to use `npm` command in this case?

**2, How can I enable `unit test` on Bitbucket Pipelines?**
I saw the document how to enable unit test [here](https://catalog.workshops.aws/complete-aws-sam/en-US/module-4-cicd/module-4-cicd-codepipeline/70-unittests) but it's just for [CodePipeline](https://catalog.workshops.aws/complete-aws-sam/en-US/module-4-cicd/module-4-cicd-codepipeline) and [GitHub](https://catalog.workshops.aws/complete-aws-sam/en-US/module-4-cicd/module-4-cicd-gh). So how about **Bitbucket Pipelines** please?

Many thanks!

**Comment by jfuss** [comment]
@danhnguyeen https://github.com/aws/aws-sam-cli-pipeline-init-templates or https://github.com/aws/aws-sam-cli is a better spot for this question, as it really doesn't relate to this repo. We own all of them so will answer here.

> 1, How to run npm in pipeline?

This doesn't really relate to SAM CLI and is more about Bitbucket pipelines. https://support.atlassian.com/bitbucket-cloud/docs/javascript-nodejs-with-bitbucket-pipelines/ maybe helpful but seems like this it's mostly based on what this is set to: https://github.com/aws/aws-sam-cli-pipeline-init-templates/blob/main/Bitbucket-Pipelines/two-stage-pipeline-template/%7B%7Bcookiecutter.outputDir%7D%7D/bitbucket-pipelines.yml#L4. 

In terms on the "So I tried to install node 18 by myself but it throws this error GLIBC_2.28' not found.", is saying the system is not compatible with node 18 as you need `GLIBC_2.28`. So you would have to upgrade glibc but that likely breaks other things. 

You maybe able to move to the node build images (if everything is node based). The comment here: https://github.com/aws/aws-sam-cli-pipeline-init-templates/blob/main/Bitbucket-Pipelines/two-stage-pipeline-template/%7B%7Bcookiecutter.outputDir%7D%7D/bitbucket-pipelines.yml#L1-L3 describes where to find that.

> 2, How can I enable unit test on Bitbucket Pipelines?

This is also more about Bitbucket Pipelines than SAM CLI. Editing the pipeline to what you need is something best for you to handle or reaching out to Bitbucket sources for more help. My assumption is you can run your tests within the https://github.com/aws/aws-sam-cli-pipeline-init-templates/blob/main/Bitbucket-Pipelines/two-stage-pipeline-template/%7B%7Bcookiecutter.outputDir%7D%7D/bitbucket-pipelines.yml#L11 block, which should be whatever commands you do to run the test within your package. If you have a `sam init` application, this is called out in the README.

Closing this as it's not related to this repo and the questions target about Bitbucket Pipeline not SAM CLI. If you need further help, feel free to create a new issue, as we do not monitor closed issues.
